steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'install']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image:latest', '.' ]
#images: ['gcr.io/$PROJECT_ID/quickstart-image:$COMMIT_SHA']
images: ['gcr.io/$PROJECT_ID/quickstart-image:latest']

steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'tomcat-1'
  - 'my-tomcat=gcr.io/$PROJECT_ID/quickstart-image:latest'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'